CAPACITY = 10000
CORRIDOR_CAPACITY = 100
BUDGET = 2000000
NUM_ROOM_TYPES = 10
NUM_ITERATIONS = 1

NUM_BEES = 100
NUM_STRICTLY_BEST_BEES = 15
NUM_BEST_BEES = 30

RANDOM_PERCENT = 0.3
BEES_FOR_TOP_BEST = int((1-RANDOM_PERCENT)*NUM_BEES*2/3)
BEES_FOR_DOWN_BEST = int((1-RANDOM_PERCENT)*NUM_BEES*1/3)
BEES_RANDOM = NUM_BEES - (NUM_STRICTLY_BEST_BEES*BEES_FOR_TOP_BEST + (NUM_BEST_BEES-NUM_STRICTLY_BEST_BEES)*BEES_FOR_DOWN_BEST)
